In [38]:
import numpy as np
import pandas as pd

In [39]:
df=pd.read_csv('/content/customer.csv')

In [40]:
df.sample(5)

    age  gender   review education purchased
20   57  Female  Average    School       Yes
23   96  Female     Good    School        No
42   30  Female     Good        PG       Yes
38   45  Female     Good    School        No
4    16  Female  Average        UG        No

In [41]:
df=df.iloc[:,2:]

In [42]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [43]:
from sklearn.model_selection import train_test_split
X_train , X_test,y_train ,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,)

In [44]:
X_train

     review education
48     Good        UG
5   Average    School
13  Average    School
17     Poor        UG
25     Good    School
29  Average        UG
36     Good        UG
37  Average        PG
12     Poor    School
24  Average        PG
15     Poor        UG
14     Poor        PG
16     Poor        UG
46     Poor        PG
44  Average        UG
2      Good        PG
43     Poor        PG
23     Good    School
40     Good    School
30  Average        UG
34  Average    School
11     Good        UG
18     Good    School
49     Good        UG
47     Good        PG
45     Poor        PG
0   Average    School
4   Average        UG
31     Poor    School
42     Good        PG
10     Good        UG
8   Average        UG
27     Poor        PG
33     Good        PG
21  Average        PG
9      Good        UG
20  Average    School
41     Good        PG
38     Good    School
39     Poor        PG

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
X_train

     review education
48     Good        UG
5   Average    School
13  Average    School
17     Poor        UG
25     Good    School
29  Average        UG
36     Good        UG
37  Average        PG
12     Poor    School
24  Average        PG
15     Poor        UG
14     Poor        PG
16     Poor        UG
46     Poor        PG
44  Average        UG
2      Good        PG
43     Poor        PG
23     Good    School
40     Good    School
30  Average        UG
34  Average    School
11     Good        UG
18     Good    School
49     Good        UG
47     Good        PG
45     Poor        PG
0   Average    School
4   Average        UG
31     Poor    School
42     Good        PG
10     Good        UG
8   Average        UG
27     Poor        PG
33     Good        PG
21  Average        PG
9      Good        UG
20  Average    School
41     Good        PG
38     Good    School
39     Poor        PG

In [47]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [48]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [49]:
X_train=oe.transform(X_train)

In [50]:
X_train

array([[2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.]])

In [51]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [52]:
X_train

array([[2., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.]])

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
le=LabelEncoder()

In [55]:
le.fit(y_train)

LabelEncoder()

In [56]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [57]:
y_train

48    Yes
5     Yes
13     No
17    Yes
25     No
29    Yes
36    Yes
37    Yes
12     No
24    Yes
15     No
14    Yes
16    Yes
46     No
44     No
2      No
43     No
23     No
40     No
30     No
34     No
11    Yes
18     No
49     No
47    Yes
45    Yes
0      No
4      No
31    Yes
42    Yes
10    Yes
8      No
27     No
33    Yes
21     No
9     Yes
20    Yes
41    Yes
38     No
39     No
Name: purchased, dtype: object

In [58]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [59]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0])