In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/gaming_addiction.csv')

df

,user_id,age,gender,country,occupation,income_level,years_gaming,preferred_genre,platform,device_type,...,absenteeism_days,internet_speed_mbps,screen_time_total_hours,behavioral_cluster,addiction_score,addiction_binary,addiction_severity,burnout_probability,mental_health_risk_score,churn_probability
0,USR000001,21,Male,India,Employed,Middle,9,Sandbox,PC,Laptop,...,7,39.9,5.4,Casual Enjoyer,27.61,0,Mild,1.0,0.920,1.000
1,USR000002,25,Male,India,Employed,Lower-Middle,13,RPG,Mobile,Mixed,...,6,71.5,13.4,Streamer/Creator,55.51,1,Moderate,1.0,0.515,0.813
2,USR000003,26,Male,Brazil,Employed,Middle,14,RPG,PC+Mobile,High-end PC,...,7,119.4,12.3,Streamer/Creator,45.85,0,Moderate,1.0,0.720,0.947
3,USR000004,22,Male,South Korea,Employed,Upper-Middle,10,Strategy,PC+Mobile,Mobile,...,8,136.5,6.9,Toxic Competitor,39.87,0,Mild,1.0,0.520,0.660
4,USR000005,17,Female,India,Student,Middle,5,Strategy,PC,Laptop,...,6,78.8,9.3,Competitive Grinder,46.97,0,Moderate,1.0,0.585,0.867
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,USR000246,23,Female,Japan,Streamer/Content Creator,Upper-Middle,11,MMORPG,PC+Console,Console,...,4,180.9,7.2,Streamer/Creator,42.37,0,Moderate,1.0,0.395,0.590
246,USR000247,18,Male,India,Student,Low,6,Sandbox,PC,Mid-range PC,...,0,91.5,5.6,Social Gamer,22.45,0,Mild,1.0,0.715,0.803
247,USR000248,20,Male,USA,Student,Middle,8,MMORPG,Mobile,Console,...,8,120.6,4.9,Escape Seeker,34.76,0,Mild,1.0,0.410,0.939
248,USR000249,19,Male,South Korea,Employed,Middle,7,Sandbox,PC+Console,High-end PC,...,2,175.9,5.2,Social Gamer,36.60,0,Mild,1.0,0.405,0.870
249,USR000250,27,Male,USA,Unemployed,Middle,14,MMORPG,PC+Mobile,Laptop,...,4,131.7,4.8,Social Gamer,41.65,0,Moderate,1.0,0.605,0.733

##Read Data in a TSV Format

In [ ]:
tf= pd.read_csv("/content/demo_mlexpec.tsv",sep='/t',header=1)
tf

/tmp/ipykernel_2339/3686381931.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  tf= pd.read_csv("/content/demo_mlexpec.tsv",sep='/t',header=1)

      YR,F,Y1,AL\t: \t79.4 \t80.4 \t80.2 \t79.7 \t79.8 \t79.2 \t79.8 \t79.6 \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t: \t:
0      YR,F,Y1,AM\t: \t: \t79.1 \t79.2 \t78.5 \t78.0 ...
1      YR,F,Y1,AT\t: \t82.9 \t83.5 \t83.3 \t83.2 \t83...
2      YR,F,Y1,AZ\t: \t: \t78.6 \t78.1 \t77.7 \t: \t7...
3      YR,F,Y1,BE\t: \t82.3 \t83.6 \t83.2 \t83.2 \t83...
4      YR,F,Y1,BG\t: \t76.9 \t78.2 \t78.0 \t77.9 \t78...
...                                                  ...
14442  YR,T,Y_LT1,SM\t: \t: \t: \t: \t: \t: \t: \t: \...
14443  YR,T,Y_LT1,TR\t: \t: \t79.1 \t78.9 \t78.5 \t78...
14444  YR,T,Y_LT1,UA\t: \t: \t73.4 \t73.2 \t73.3 \t72...
14445  YR,T,Y_LT1,UK\t: \t: \t: \t81.3 \t81.3 \t81.2 ...
14446  YR,T,Y_LT1,XK\t: \t: \t: \t: \t: \t78.6 p\t: \...

[14447 rows x 1 columns]

##Use requried column only

In [ ]:
pd.read_csv('/content/life_expectancy.csv',usecols=['Country'])

                      Country
0                        Chad
1                     Nigeria
2                 South Sudan
3                     Lesotho
4    Central African Republic
..                        ...
195               Switzerland
196      United Arab Emirates
197                 Australia
198                 Hong Kong
199                Micronesia

[200 rows x 1 columns]

#Change the encoading if not in UTF-8

In [ ]:
pd.read_csv('/content/netflix_titles.csv',encoding='latin-1')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8807,s8808,TV Show,Parasyte: The Grey,Yeon Sang-ho,"Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan",South Korea,"April 5, 2024",2024,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8808,s8809,Movie,Serena,Susanne Bier,"Bradley Cooper, Jennifer Lawrence, Toby Jones,...",United States,"April 5, 2024",2014,A,110 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#If any row has many or less values then

In [ ]:
pd.read_csv('/content/sample_data/california_housing_test.csv',on_bad_lines='skip')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
pd.read_csv("/content/IPL_Ball_by_Ball_2008_2022.csv",usecols=['bowler','batter','batsman_run']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   batter       225954 non-null  object
 1   bowler       225954 non-null  object
 2   batsman_run  225954 non-null  int64
dtypes: int64(1), object(2)
memory usage: 5.2+ MB

In [ ]:
pd.read_csv("/content/IPL_Ball_by_Ball_2008_2022.csv")

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [ ]:
def rename(name):
  if name == "Rajasthan Royals":
    return "RR"
    if name == "Royal Challengers Bangalore":
       return "RCB"
  else :
    return name

In [ ]:
pd.read_csv("/content/IPL_Ball_by_Ball_2008_2022.csv",converters={'BattingTeam':rename})

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,RR
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,RR
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,RR
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,RR
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,RR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

#Making a chunks and loading them

In [ ]:
dfs = pd.read_csv("/content/IPL_Ball_by_Ball_2008_2022.csv",chunksize=5000)

In [ ]:
for chunk in dfs:
    print(chunk.shape)

(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(5000, 17)
(954, 17)